name: Fly Deploy - Core
on:
   push:
      branches:
         - main
jobs:
   deploy:
      name: Deploy core app
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: superfly/flyctl-actions/setup-flyctl@master
         - run: flyctl deploy --config ./fly/core/fly.toml --remote-only
           env:
              FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
